name: QA Automation CI

on: [push, pull_request]

jobs:
  automation-tests:
    runs-on: ubuntu-latest
    
    # Запускаем базу данных прямо в GitHub
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_api_qa
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t qa-project-chaos .

      - name: Run all tests
        # Добавляем переменные окружения, чтобы перекрыть локальные настройки
        run: |
          docker run --rm \
          --network host \
          -e DB_HOST=localhost \
          -e DB_USER=postgres \
          -e DB_PASSWORD=password \
          -e DB_NAME=test_api_qa \
          -e PYTHONPATH=/app \
          qa-project-chaos pytest tests/